name: blitz
description: blitz through the

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.6.1
  geolocator: ^11.0.0
  lottie: ^3.1.1
  timelines_plus: ^1.0.2
  http: ^1.2.1
  flutter_polyline_points: ^2.0.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  otp_text_field: ^1.1.3
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.1
  carousel_slider: ^4.2.1
  flutter_stripe: ^10.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: assets/icons/logo.png

flutter:
  uses-material-design: true

  fonts:
    - family: UberMoveMedium
      fonts:
        - asset: fonts/UberMoveMedium.otf
    - family: UberMoveBold
      fonts:
        - asset: fonts/UberMoveBold.otf

  assets:
    - assets/images/logo.png
    - assets/images/card.png
    - assets/images/animation.gif
    - assets/images/moaca.png
    - assets/images/visa.png
    - assets/images/mastercard.png
